fix bug：1、修改扫描页面的UI；2、首页吊起扫码页面获取权限授权之后不直接进入到扫描页面；3、扫码页面添加 打开/关闭手电筒 4：…
OneKeyHQ/electrum pull request #139
Opened 2020-12-11 11:02 UTC by peterQin0826

fix bug：1、修改扫描页面的UI；2、首页吊起扫码页面获取权限授权之后不直接进入到扫描页面；3、扫码页面添加 打开/关闭手电筒 4：…

2020-12-14 08:36 UTC, xmstrawberry approved these changes

2020-12-14 08:39 UTC, liyanhrxy approved these changes

2020-12-14 09:28 UTC, danielsocials requested changes

2020-12-14 09:28 UTC, danielsocials commented on android/app/src/main/java/org/haobtc/onekey/utils/PwdEditText.java
> +//            if (mText.length() >= i) {
无用代码需要删除

2020-12-14 09:28 UTC, danielsocials commented on android/zxinglibrary/src/main/java/com/yzq/zxinglibrary/android/CaptureActivity.java
> +//                    Log.d("xiaopeng", "扫描异常-------");
无用调试代码需要删除

2020-12-14 09:28 UTC, danielsocials commented on android/zxinglibrary/src/main/java/com/yzq/zxinglibrary/decode/DecodeImgThread.java
> +//              Log.i("解析的图片结果","失败");
同上

2020-12-14 09:28 UTC, danielsocials commented on android/app/src/main/java/org/haobtc/onekey/onekeys/homepage/WalletFragment.java
> +                                    LogUtil.d("xiaopeng", "授权了============");// Always true pre-M
log信息的tag需要合理的分类，比如模块名称，开发者名字不是一个好的方式

2020-12-14 09:28 UTC, danielsocials commented on android/app/src/main/java/org/haobtc/onekey/onekeys/backup/BackupGuideActivity.java
>  }
末尾加空行，见https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

2020-12-14 09:28 UTC, danielsocials commented on android/zxinglibrary/src/main/java/com/yzq/zxinglibrary/view/ViewfinderView.java
> +
无用空行？

2020-12-15 05:54 UTC, peterQin0826 commented on android/app/src/main/java/org/haobtc/onekey/utils/PwdEditText.java
> +//            if (mText.length() >= i) {
收到

2020-12-15 07:38 UTC, peterQin0826 commented on android/zxinglibrary/src/main/java/com/yzq/zxinglibrary/view/ViewfinderView.java
> +
解决，格式化的工具我再研究下

2020-12-15 09:55 UTC, merged