Enable pre-commit for python
OneKeyHQ/electrum pull request #244
Opened 2021-01-02 07:57 UTC by huazhouwang

## What does this implement/fix? Explain your changes.
* enable pre-commit for python
  * only some basic features are enabled now
  * flake8 and bandit will be enabled later

## Does this close any currently open issues?  
If it fixes a bug or resolves a feature request, be sure to link to that issue.
…

## Pull request type
 
_Put an `x` in the boxes that apply_
- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Where has this been tested?
…

## Any other comments?
After this PR merged, everyone should do please:
* pip install pre-commit
* pre-commit install

2021-01-02 07:58 UTC, huazhouwang commented
@shuaiLiWang 我加入了 pre-commit ，有空帮忙看下 PR

2021-01-03 02:22 UTC, danielsocials requested changes

2021-01-03 02:22 UTC, danielsocials commented on .pre-commit-config.yaml
> +#-   repo: https://github.com/PyCQA/bandit
删除无用代码

2021-01-03 02:22 UTC, danielsocials commented on .pre-commit-config.yaml
> +#-   repo: https://gitlab.com/pycqa/flake8
删除无用代码

2021-01-03 02:22 UTC, danielsocials commented on .pre-commit-config.yaml
> +-   repo: https://github.com/asottile/seed-isort-config
seed-isort-config is DEPRECATED?

2021-01-03 02:22 UTC, danielsocials commented on android/app/generate_strings.py
>  import argparse
wrong change file?

2021-01-03 02:22 UTC, danielsocials commented on .pre-commit-config.yaml
> +        exclude: /(migrations|_pb2)/
migration|_pb2?

2021-01-03 02:22 UTC, danielsocials commented on .pre-commit-config.yaml
> +-   repo: https://github.com/psf/black
black是否会强制format代码，style是否可以适配存在的electrum的风格？考虑到已经存在大量electrum/trezor代码，代码风格这里先只做检查，让coder自己选择去format

2021-01-03 02:22 UTC, danielsocials commented on .pre-commit-config.yaml
> +    rev: v3.1.0
为什么不选择最新版本？

2021-01-03 02:22 UTC, danielsocials commented on android/app/build.gradle
> +            def matcher = it =~ / *ELECTRUM_VERSION *= *"([0-9.]+)".*/
这里具体是fix了什么问题？

2021-01-03 04:11 UTC, huazhouwang commented
ack, 有些考虑不周的地方，我修改下

2021-01-03 04:50 UTC, closed without merging