Add the Google Play Channel Pack
OneKeyHQ/electrum pull request #342
Opened 2021-01-20 13:05 UTC by QuincySx

## What does this implement/fix? Explain your changes.
+ Add the Google Play Channel Pack
+ Optimize and upgrade experience

## Does this close any currently open issues?  
If it fixes a bug or resolves a feature request, be sure to link to that issue.
OneKeyHQ/TaskHub#686

## Pull request type
 
_Put an `x` in the boxes that apply_
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Where has this been tested?
Local test

## Any other comments?
None

2021-01-20 13:12 UTC, QuincySx commented
App build output 文件夹格式:
MainNetOnekey
MainNetGooglePlay
RegTestOnekey
RegTestGooglePlay
等等

单独打包命令
assembleMainNetGooglePlayDebug
assembleMainNetGooglePlayRelease
assembleMainNetOnekeyRelease
等等

2021-01-21 02:55 UTC, peterQin0826 approved these changes

2021-01-22 07:33 UTC, danielsocials requested changes
对testnet/regtest版本, 不需要区分appstore,都不会走google play

2021-01-22 09:27 UTC, QuincySx commented
暂时不要合并

2021-01-22 11:02 UTC, merged