Modify the transfer logic
OneKeyHQ/electrum pull request #377
Opened 2021-01-27 03:10 UTC by peterQin0826

## What does this implement/fix? Explain your changes.
修改Eth转账逻辑，自定义费率和最大值本地计算，不依赖接口

## Does this close any currently open issues?  
If it fixes a bug or resolves a feature request, be sure to link to that issue.
OneKeyHQ/TaskHub#633
OneKeyHQ/TaskHub#720
## Pull request type
 
_Put an `x` in the boxes that apply_
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Where has this been tested?
…

## Any other comments?
…

2021-01-27 03:18 UTC, QuincySx approved these changes

2021-01-27 05:47 UTC, danielsocials requested changes
need rebase

2021-01-28 05:01 UTC, QuincySx approved these changes

2021-01-28 05:01 UTC, QuincySx approved these changes

2021-01-28 06:43 UTC, merged