ETH - Add Geth explorer
OneKeyHQ/electrum pull request #422
Opened 2021-02-01 23:56 UTC by huazhouwang

## What does this implement/fix? Explain your changes.
1. 封装 JsonPRCRequest
2. 统一对外暴露 new_restful 和 new_json_rpc, 而不是直接调用 RestfulRequest 和 JsonRPCRequest
3. 新增 Geth Explorer 支持

## Does this close any currently open issues?  
If it fixes a bug or resolves a feature request, be sure to link to that issue.
…

## Pull request type
 
_Put an `x` in the boxes that apply_
- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Where has this been tested?
…

## Any other comments?
…

2021-02-02 09:04 UTC, taimanhui approved these changes
没看出来隐藏类名改用函数调用有什么特别的好处

另外无关改动不少，考虑处理一下

2021-02-02 09:04 UTC, taimanhui commented on electrum_gui/common/explorer/clients/eth/trezor.py
> -
无关改动

2021-02-02 09:04 UTC, taimanhui commented on electrum_gui/common/explorer/data/interfaces.py
> +        :raise: raise TransactionNotFound if target tx not found
无关改动

2021-02-02 13:37 UTC, shuaiLiWang approved these changes

2021-02-02 14:26 UTC, huazhouwang commented on .flake8
> +exclude = .git, __init__.py
我在 `electrum_gui/common/explorer/clients/__init__.py` 里会导出内部实现，我原本试过每行都加 `# noqa`，但感觉有点多，所以加了忽略。请问 flake8 能否做到指定 `__init__.py` 文件忽略仅忽略特定异常吗？

2021-02-02 14:35 UTC, huazhouwang commented on electrum_gui/common/basic/request/interfaces.py
> +            method=Method.POST, path=path, data=data, json=json, headers=headers, timeout=timeout, **kwargs
虽然这一行没有改动，但因为对这个文件改动，pre-commit 会统一格式化

2021-02-02 14:37 UTC, huazhouwang commented on electrum_gui/common/basic/request/json_rpc.py
> +        self.inner = new_restful(
相对于继承我会更偏向于使用组合，继承会给类带来多余的变量和方法

2021-02-02 14:41 UTC, huazhouwang commented on electrum_gui/common/basic/request/json_rpc.py
> +        resp = self.inner.post("", json=payload, timeout=timeout, headers=headers, **kwargs)
嗯，可以。之前我理解大部分情况下 jsonrpc 的 url 可以一开始实例化时就已经确定了，后续没有指定 path 的意义

2021-02-02 14:53 UTC, huazhouwang commented on electrum_gui/common/basic/request/json_rpc.py
> +def new_json_rpc(
类似上面提到的，我倾向于组合而不是继承。隐藏 `_JsonRPCRequest` 可以强制外部通过组合方式来使用。同时还能隐藏内部实现细节，假设 JsonRPCRequest 继承自 RestfulRequest ，且不隐藏的话，外部就可以用 JsonRPCRequest 做 restful 的事情，这就跟封装的初衷不符了

2021-02-02 14:57 UTC, huazhouwang commented on electrum_gui/common/explorer/clients/eth/geth.py
> +                ("eth_getTransactionCount", [address, self.__LAST_BLOCK__]),
嗯，好问题。是否会有争抢具体要看 rpc 服务端的实现。目前看这种影响不大，且如果指定区块的话会带来额外请求最新区块的请求量

2021-02-02 15:01 UTC, huazhouwang commented on electrum_gui/common/explorer/clients/eth/geth.py
> +        require(txid == tx.get("hash"))
> require应该跟到tx的检查之后？

这个仅作为类断言的作用，几乎不可能带来影响，方便判断服务端是否异常

> receipt的判断下面几处...的分支判断好点吧

嗯，这个我改下

2021-02-02 15:02 UTC, huazhouwang commented on electrum_gui/common/explorer/clients/eth/geth.py
> +        return []
Geth 无法搜索某个地址的所有交易记录，所以他仅能返回空数据

2021-02-02 15:04 UTC, huazhouwang commented on electrum_gui/common/explorer/clients/eth/trezor.py
> -
因为移动了文件，触发了 pre-commit

2021-02-02 15:04 UTC, huazhouwang commented on electrum_gui/common/explorer/data/interfaces.py
> +        :raise: raise TransactionNotFound if target tx not found
这个是我在实现 Geth 时候意识到需要更加明细 get_transaction_by_txid 的描述

2021-02-02 15:07 UTC, huazhouwang commented on electrum_gui/common/basic/dataclass/dataclass.py
> +            data = {k: Decimal(v) if k in decimal_fields else v for k, v in data.items()}
嗯，后续尽量避免这种改动。这次主要是之前 pre-commit  的配置有变动，触发了 pre-commit

2021-02-02 15:12 UTC, huazhouwang commented
@taimanhui 要不咱们找个时间，你，我和帅姐一起聊聊编码和代码提交相关的规范如何？我觉得现在是个很好的时机诶

2021-02-03 02:21 UTC, huazhouwang commented on .flake8
> +exclude = .git, __init__.py
已找到解决办法，用 `per-file-ignores` 配置，仅忽略 __init__.py 的 `F401` 警告，如何？

2021-02-03 03:57 UTC, taimanhui commented on .flake8
> +exclude = .git, __init__.py
相比较而言加上`#noqa`会更常见，主要应该是能在`__init__.py`里显式说明某几行代码是有意break codestyle的，比这样隐式要好。不过没必要纠结这个，应该都能知道怎么回事。

例子
- https://github.com/django/django/search?q=noqa
- https://github.com/falconry/falcon/blob/master/falcon/__init__.py

另外其实有个更tricky的做法也能绕过这个问题，用`__all__ = [...]`应该就不算imported but not used了（没试过）哈哈...

2021-02-03 04:01 UTC, taimanhui commented on electrum_gui/common/basic/dataclass/dataclass.py
> +            data = {k: Decimal(v) if k in decimal_fields else v for k, v in data.items()}
嗯，尽量避免自动化工具改了不该改的地方，主要是以后看历史的话不一定能记得这是pre-commit改的...

最好还是去掉他们，实在不想动还想包含进来的话，建议你在commit message里面给个列表说明一下哪些文件里有格式改动/空格改动，这样子几个月后看到这个无关改动想骂人不会到你身上，是pre-commit干的。

2021-02-03 04:17 UTC, taimanhui commented on electrum_gui/common/basic/request/json_rpc.py
> +    @classmethod
其实这两者实际上区别不是很大，但既然都存在还是不要混用比较好。简单版本的话不需要用到`cls`/`self`的都应该是`staticmethod`。个人理解classmethod是一些会以类为单位去调用的内容，比如常见用来实现构造函数之类的。staticmethod侧重于将类里面一部分代码逻辑抽象并组织起来。

> 需要经常在 staticmethod 和 classmethod 之前切换

实践中有这种情况不假，但不建议太过考虑这些情况然后做太多预留。如果在类似地方留个注释「以后可能会变成类方法所以先直接就用了」，预留的时候我们总觉得开盅时会是「6个月小」，但通常揭晓的时候总是「超过15个月大」。

参考：https://stackoverflow.com/questions/136097/difference-between-staticmethod-and-classmethod

2021-02-03 04:27 UTC, huazhouwang commented on electrum_gui/common/basic/dataclass/dataclass.py
> +            data = {k: Decimal(v) if k in decimal_fields else v for k, v in data.items()}
好的，我先把这个改动去掉

2021-02-03 04:28 UTC, huazhouwang commented on .flake8
> +exclude = .git, __init__.py
了解，目前我打算先用 `per-file-ignores` 忽略 `__init__.py` 的 F401 警告哈

2021-02-03 04:32 UTC, taimanhui commented on electrum_gui/common/basic/request/json_rpc.py
> +def new_json_rpc(
但是这个函数并没有实现什么隐藏的功能啊，它唯一的作用只是将其他地方用到`JsonRPCRequest()`的地方变成了`new_json_rpc()`，其他逻辑没有什么特别的不同，反而造成的不便是我去看某个实例的时候，不能直接知道它是一个什么东西，还要跟到这个函数里看它做了什么。Python代码很少见到这种额外的隔离。

至于你说的「不隐藏的话，外部就可以用 JsonRPCRequest 做 restful 的事情」，其实隐不隐藏也都一样能做；这个点对上面那个使用组合而不是继承来说是合理的，这样子后面看代码时能外部看到是否显式用了那个`inner`；但也不是必须的，python代码一般不特别做这种限制，逻辑上的东西是项目组织的锅，不关代码本身的事。

2021-02-03 04:33 UTC, taimanhui commented on electrum_gui/common/explorer/clients/eth/geth.py
> +                ("eth_getTransactionCount", [address, self.__LAST_BLOCK__]),
嗯，应该可以忽略不计，留个comment说明也好

2021-02-03 04:36 UTC, taimanhui commented on electrum_gui/common/explorer/clients/eth/geth.py
> +        require(txid == tx.get("hash"))
> 这个仅作为类断言的作用，几乎不可能带来影响，方便判断服务端是否异常

我知道这个是断言，但断言本来就应该用在最早能用的地方，你总不会把它放到最后的return之前对吧；按这个逻辑断言之前先其他方面的检查都不合理的。

2021-02-03 04:37 UTC, taimanhui commented on electrum_gui/common/explorer/clients/eth/geth.py
> +        return []
嗯，留个comment吧，否则不知道是准备实现还是不准备实现。

2021-02-03 04:39 UTC, huazhouwang commented on electrum_gui/common/explorer/clients/eth/geth.py
> +        require(txid == tx.get("hash"))
嗯，理解了，已经提前到「最早能用的地方」

2021-02-03 04:41 UTC, huazhouwang commented on electrum_gui/common/basic/request/json_rpc.py
> +    @classmethod
行，我以后会注意 `staticmethod` 和 `classmethod`，可能后续还会一不小心忽略，帮忙及时提出哈，多谢

2021-02-03 04:50 UTC, huazhouwang commented on electrum_gui/common/basic/request/json_rpc.py
> +def new_json_rpc(
嗯，像你说的，虽然对 Python 来说，加个函数实际并不能起到隐藏作用，但配合 typing 和 IDE 提醒的话，还是能一定程度避免外部调用了不该调用的方法，因为我在函数返回的是接口

2021-02-03 04:53 UTC, huazhouwang commented on electrum_gui/common/explorer/clients/eth/geth.py
> +        return []
ack

2021-02-03 05:01 UTC, taimanhui approved these changes
jsonrpc里面那个jsonlize需要再看看

其他的无问题了。

前面一些comment被隐藏了我还是有回复，可以展开看看，都不是大问题

2021-02-03 05:02 UTC, huazhouwang commented on electrum_gui/common/explorer/clients/eth/geth.py
> +                ("eth_getTransactionCount", [address, self.__LAST_BLOCK__]),
嗯，我想想 comment 怎么写合适

2021-02-03 05:04 UTC, huazhouwang commented on electrum_gui/common/basic/request/json_rpc.py
> +    @classmethod
ack

2021-02-03 05:07 UTC, taimanhui commented on electrum_gui/common/basic/request/json_rpc.py
> +        self.response_jsonlize = response_jsonlize
如果确认不需要的话，应该从外部就抛弃这个了，总是使用`True`去调用`new_restful`就可以了

2021-02-03 05:08 UTC, huazhouwang commented on electrum_gui/common/explorer/clients/eth/geth.py
> +        gas_usage = _hex2int(receipt.get("gasUsed", "0x0")) if receipt else None
ack

2021-02-03 05:10 UTC, huazhouwang commented on electrum_gui/common/basic/request/json_rpc.py
> +        self.response_jsonlize = response_jsonlize
这个就类似 `call` 和 `batch_call` 里加上  `path` 参数一样，虽然确实不合理，但我之前对接过类似服务

2021-02-03 05:16 UTC, taimanhui commented on electrum_gui/common/basic/request/json_rpc.py
> +        self.response_jsonlize = response_jsonlize
好吧，RestfulRequest里的path也不是常规意义上的path...

我理解的path是[RFC3986](https://tools.ietf.org/html/rfc3986#section-3)里说明这样的，所以request请求有path是正常的，为空我反而感觉奇怪...

2021-02-03 05:24 UTC, huazhouwang commented on electrum_gui/common/basic/request/json_rpc.py
> +        self.response_jsonlize = response_jsonlize
行，我先把 `response_jsonlize` 去掉

2021-02-03 05:38 UTC, huazhouwang commented on electrum_gui/common/explorer/clients/eth/geth.py
> +                ("eth_getTransactionCount", [address, self.__LAST_BLOCK__]),
想了半天想不出 comment 怎么写诶，请问有什么建议吗？

2021-02-03 06:15 UTC, huazhouwang commented
@taimanhui 所有的 comment 我都检查了一遍，就只剩下 `new_json_rpc` 和 `new_restful` 的封装还有些不同的意见。我还是希望能保留函数，其实 python 也有很多函数封装的用法

2021-02-03 06:43 UTC, taimanhui commented
> @taimanhui 所有的 comment 我都检查了一遍，就只剩下 `new_json_rpc` 和 `new_restful` 的封装还有些不同的意见。我还是希望能保留函数，其实 python 也有很多函数封装的用法

这两个倒无所谓，其实区别不大，只是少见而已

2021-02-03 07:10 UTC, huazhouwang commented
好的，那我先过了

2021-02-03 10:04 UTC, danielsocials requested changes

2021-02-03 10:27 UTC, huazhouwang commented
好的，统一风格

2021-02-03 13:15 UTC, huazhouwang commented
@danielsocials 已改，有空帮忙看下

2021-02-04 02:13 UTC, danielsocials approved these changes

2021-02-04 02:13 UTC, merged