add mvp framework  and ble logic
OneKeyHQ/electrum pull request #46
Opened 2020-10-22 14:08 UTC by LiHu20160316

2020-10-23 03:59 UTC, danielsocials requested changes
pr里面不要包括不是自己的修改
最好不要有merge xxx的commit

2020-10-23 04:06 UTC, danielsocials reviewed
submodule不需要改

2020-10-23 04:06 UTC, danielsocials commented on android/app/build.gradle
> +            buildConfigField "Boolean", "IS_DEBUG", "true"
调试开关，默认不要打开

2020-10-23 04:06 UTC, danielsocials commented on android/app/version.properties
> +#Thu Oct 22 01:00:10 CST 2020
这个文件不需要提交，编译时的文件自动会改

2020-10-23 04:06 UTC, danielsocials commented on android/app/src/main/java/org/haobtc/onekey/passageway/BlePassageway.java
> +//                        bleTransport.put("ENABLED", true);
无关代码删除

2020-10-27 09:23 UTC, liyanhrxy approved these changes

2020-10-27 09:23 UTC, liyanhrxy approved these changes

2020-10-30 02:46 UTC, liyanhrxy approved these changes

2020-10-30 02:46 UTC, liyanhrxy commented on android/app/version.properties
>  }=
这个文件 `android/app/version.properties `  不要提交

2020-10-30 02:50 UTC, liyanhrxy approved these changes

2020-10-30 02:50 UTC, liyanhrxy commented on android/app/src/main/AndroidManifest.xml
> -<<<<<<< HEAD
对同一个文件的修改建议不要放在两个commit里面

2020-10-30 02:52 UTC, liyanhrxy approved these changes
对同一个文件的修改，建议最好放在同一个commit里面

2020-10-30 03:08 UTC, danielsocials requested changes

2020-10-30 03:09 UTC, danielsocials commented
@LiHu20160316  ci build 失败需要处理

2020-11-05 02:31 UTC, danielsocials approved these changes

2020-11-05 02:31 UTC, merged