ios feat: Add thumbnail for displaying share action sheet
OneKeyHQ/electrum pull request #521
Opened 2021-02-28 09:03 UTC by Umiiii

## What does this implement/fix? Explain your changes.
Add thumbnail and title while displaying share action sheet
Remove iOS 8 compatibility code.

## Does this close any currently open issues?  
https://github.com/OneKeyHQ/TaskHub/issues/255 

## Pull request type
 
_Put an `x` in the boxes that apply_
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Where has this been tested?
…

## Any other comments?
…

2021-03-01 03:57 UTC, liuzjalex approved these changes

2021-03-01 04:30 UTC, liuzjalex requested changes
git没有追踪工程文件，新增加文件需要执行下 copy_back_changes.sh

2021-03-01 13:53 UTC, Umiiii commented
> git没有追踪工程文件，新增加文件需要执行下 copy_back_changes.sh

@liuzjalex 已经加好了工程文件的changes

2021-03-02 03:01 UTC, liuzjalex approved these changes

2021-03-03 09:11 UTC, danielsocials approved these changes

2021-03-03 09:11 UTC, merged