add support for starcoin
OneKeyHQ/electrum pull request #706
Opened 2021-04-13 03:39 UTC by dydysy

## What does this implement/fix? Explain your changes.

starcoin 币种支持。

## Does this close any currently open issues?  
https://github.com/OneKeyHQ/TaskHub/issues/964

## Pull request type
 
_Put an `x` in the boxes that apply_
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Where has this been tested?
…

## Any other comments?
…

2021-05-18 09:06 UTC, dydysy commented
@华州  `from trezorlib import _ed25519 as ed25519`
keyinterface中 ed25519 用的这个库，能不能换成 cryptography 。
因为签名长度不一致。   我想 sol 应该也测试不能通过吧 @李琰

2021-05-18 10:44 UTC, huazhouwang commented
@liyanhrxy 换库了，但你说的签名长度不一致是什么问题，能详细点吗？

2021-05-18 10:47 UTC, dydysy reviewed
> @liyanhrxy 换库了，但你说的签名长度不一致是什么问题，能详细点吗？

当前 keyinterface 签名后拿到的 signature， 只有32字节。  
我用cryptography 签名，得到的数据是 64字节。

2021-05-18 10:47 UTC, dydysy commented on electrum_gui/common/provider/manager.py
> +def get_balance(chain_code: str, address: str, token_address: Optional[ContractAddress] = None) -> int:
这个地方token_address. 参数变动，不确定对 app 调用 产生多大影响。

2021-05-18 10:49 UTC, dydysy commented
![image](https://user-images.githubusercontent.com/3320510/118638631-a22ce600-b809-11eb-91c0-9981daad15bf.png)
我看搜了下torzer 的代码， 应该是64字节。   至于为什么那个 trezerlib 签名数据是32字节，我也没看懂。

2021-05-18 10:54 UTC, huazhouwang commented
我测了是64字节

2021-05-18 10:55 UTC, huazhouwang commented on electrum_gui/common/provider/manager.py
> +def get_balance(chain_code: str, address: str, token_address: Optional[ContractAddress] = None) -> int:
这里我建议改成 CoinInfo，就是 coin.data 里的 CoinInfo。调用的地方都需要改下

2021-05-18 11:01 UTC, huazhouwang commented on electrum_gui/common/provider/manager.py
> +def get_balance(chain_code: str, address: str, token_address: Optional[ContractAddress] = None) -> int:
对了，如果你替换成 CoinInfo 的话，建议这个替换的过程单独一个 commit

2021-05-18 11:01 UTC, huazhouwang commented on electrum_gui/common/provider/manager.py
> +def get_balance(chain_code: str, address: str, token_address: Optional[ContractAddress] = None) -> int:
另外可以简单描述下 starcoin 如何唯一定义某个代币吗？我看 ContractAddress 里加了 name 和 module

2021-05-18 11:03 UTC, dydysy commented
> 我测了是64字节

那可能是我单元测试那里，没搞清楚。  那如果还没改就不用改了，我再试试。

2021-05-18 11:05 UTC, huazhouwang commented
你试试单步调试下看看从 Signer 里取到的结果是啥，应该是 64 字节的，我刚刚才测了

2021-05-18 11:09 UTC, huazhouwang commented
另外我在 https://github.com/OneKeyHQ/electrum/pull/739 里给 ChainInfo 加了一些属性，跟 bip44 路径生成逻辑相关的。我建议你可以拉我这个 PR 在本地走一遍创建，获取余额，获取费率，签名上链流程。

2021-05-18 13:34 UTC, dydysy commented on electrum_gui/common/provider/manager.py
> +def get_balance(chain_code: str, address: str, token_address: Optional[ContractAddress] = None) -> int:
代币发行，是挂在个人地址下面的，没有所谓的合约地址。
完整的代币访问路径是  type_parm = "{}::{}::{}".format(contract_address, module, name)
主币stc 其实也是和 代币 一个性质。 
stc 的访问路径是 `0x00000000000000000000000000000001::STC::STC`
我用 0xb61a35af603018441b06177a8820ff2a 发行的 onekey 代币的访问路径那就是
`0xb61a35af603018441b06177a8820ff2a::OneKey:Onkey`

2021-05-18 13:37 UTC, huazhouwang commented
那能把这拼接后的字符串作为 token_address 吗？因为 token_address 需要保持全局唯一，而且这样的话也没有新增字段了

2021-05-18 13:39 UTC, dydysy commented
> 那能把这拼接后的字符串作为 token_address 吗？因为 token_address 需要保持全局唯一，而且这样的话也没有新增字段了

你这个想法好， 我暂时没有觉得有什么不妥的地方。

2021-05-18 14:05 UTC, dydysy commented on electrum_gui/common/provider/manager.py
> +def get_balance(chain_code: str, address: str, token_address: Optional[ContractAddress] = None) -> int:
最后直接用 `0xb61a35af603018441b06177a8820ff2a::OneKey:Onekey` 写法来作为token address。 这样挺完美的，当时没跳出这个坑。

2021-05-19 01:23 UTC, huazhouwang commented on electrum_gui/common/provider/manager.py
> +def get_balance(chain_code: str, address: str, token_address: Optional[ContractAddress] = None) -> int:
这种拼接方式是不是官方通用做法？假设客户端直接这么展示用户能否秒懂？

2021-05-19 02:24 UTC, dydysy commented on electrum_gui/common/provider/manager.py
> +def get_balance(chain_code: str, address: str, token_address: Optional[ContractAddress] = None) -> int:
现在给出能参考的例子太少了， token的rpc转账的方法也是我猜测摸索出来的。  
explorere 功能也不完善， 也没看到怎么标注代币的。
从我现有了解的来看，   address, module, name ，三者缺一不可。

2021-05-19 09:18 UTC, huazhouwang reviewed
赞！！！
接入过程有遇到什么问题吗？有哪里不顺手吗？有的话及时提出哈

2021-05-19 09:18 UTC, huazhouwang commented on electrum_gui/common/coin/configs/chains.json
> +    "chain_model": "account",
可以看下 wallet manager 那个 PR，需要关注下新增的几个 bip44 开头的属性，应该会用到

2021-05-19 09:18 UTC, huazhouwang commented on electrum_gui/common/coin/configs/chains.json
> +        "name": "OKExChain Mainnet",
名字错了

2021-05-19 09:18 UTC, huazhouwang commented on electrum_gui/common/coin/configs/testnet_chains.json
> +    "fee_code": "fstc",
fstc 是什么？应该是 tstc 吧？

2021-05-19 09:18 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/provider.py
> +class STCProvider(ProviderInterface):
ProviderInterface 也需要关注下 wallet manager 那个 PR，有些许变动

2021-05-19 09:18 UTC, huazhouwang commented on electrum_gui/common/provider/data.py
> +    address_public_key: str = None
address_pubkey 如何？

2021-05-19 09:36 UTC, dydysy commented on electrum_gui/common/provider/data.py
> +    address_public_key: str = None
链上未激活地址，需要提供公钥。

2021-05-19 09:42 UTC, huazhouwang commented on electrum_gui/common/provider/data.py
> +    address_public_key: str = None
嗯，懂，我是说名字改下？

2021-05-19 09:45 UTC, dydysy commented on electrum_gui/common/coin/configs/chains.json
> +    "chain_model": "account",
> 赞！！！
> 接入过程有遇到什么问题吗？有哪里不顺手吗？有的话及时提出哈

我觉得挺好的。 👍

不顺手的地方，是STC新币种文档缺失，造成的。

熟悉了关键步骤后，按当前模式以后加币，应该会提升不少效率。

2021-05-19 10:10 UTC, dydysy commented on electrum_gui/common/provider/data.py
> +    address_public_key: str = None
改了，开始没懂你意思。

2021-05-19 10:30 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/provider.py
> +class STCProvider(ProviderInterface):
等你 merge 后，我这里会再测一遍。 现在APP是不会那么快发布了。

2021-05-24 17:39 UTC, taimanhui reviewed
我是一个个commit看过来，所以前面有些comment可能后面的commit处理掉了，忽略即可。

sdk的我跳过，有个问题是sdk现在看起来是整个搬过来，但是其实后面会有维护的问题。如果不能缩小规模（像eth的实现那样只依赖少部分库），那还不如直接就加上这个依赖。

其它的一路看下来没啥，我理解公私钥的部分应该不需要额外的代码了，现有的支持已经满足了，后面只需要实现wallet对吧

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        __RESOURCE_TAG: int = 1
避免用双下划线开头的命名，一个就够了。参考[这里](https://google.github.io/styleguide/pyguide.html#3162-naming-conventions)

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        type_parm = "{}::{}::{}".format(sdk_utils.CORE_CODE_ADDRESS, module, name)
parm -> param?

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            _balance = self.get_account_token(address, "STC", "STC")
为啥要多引入一个`_nonce`/`sequence_number`，只保留一个就好了啊

另外`_balance`获取的这一行放上面的`else`里就可以了吧

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        # what's different about module and name ?
`NOTE: `或者`TODO: `前缀

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        return _balance
这是一行

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        payload_oj = starcoin_stdlib.decode_script_function_payload(_payload)
`oj`是啥缩写？

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            used=gas_used or gas_limit,
pending的话直接把used设置成gas_limit好像不太好呢，不过我看原来eth的实现里也是这么做。 @huazhouwang 当时是怎么考虑的？

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        value = _value
一开始直接用receiver和value就好，没必要专门引入额外中间的变量看着眼花，另外`receiver.lower()`直接在上面`hex()`之后接就好了（是否有必要，好像直接就是小写的，不过文档里倒是没明确说明）

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        return Address(address=address, balance=_balance, nonce=_nonce, existing=_account_exists)
没太理解这里，是stc上及时余额为0同时nonce也为0，仍然可能是存在的地址？是的话就能理解了

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +                print(json_response)
多出来了

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/provider.py
> +                token_module = "STC"  # nosec
nosec是啥的检查会有问题？

2021-05-24 17:39 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/provider.py
> +            max_gas_amount=10000000,
不是从unsigned_tx里面拿fee_limit？

2021-05-25 16:04 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/provider.py
> +                token_module = "STC"  # nosec
pre-commit 提示安全问题， 可能是命名中有 token 字样。

2021-05-25 16:09 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        value = _value
> sdk的我跳过，有个问题是sdk现在看起来是整个搬过来，但是其实后面会有维护的问题。如果不能缩小规模（像eth的实现那样只依赖少部分库），那还不如直接就加上这个依赖。
> 
> 其它的一路看下来没啥，我理解公私钥的部分应该不需要额外的代码了，现有的支持已经满足了，后面只需要实现wallet对吧

sdk 大部分是搬过来的， 因为项目方提供的sdk， 使用了 numpy ， 我把numpy 的部分给替换了。  

公私钥相关方法已经够用了。   麻烦的交易信息的序列化，和反序列化，所以才把整个sdk 搬进来了。

2021-05-25 16:43 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        return Address(address=address, balance=_balance, nonce=_nonce, existing=_account_exists)
stc 其实也是需要判断 nonce 或者 余额。 不过 `__get_account_sequence_number` 已经足够判断地址是否存在了， 所以我就没有再判断 余额 和 nonce了。   写成 `(bool(_balance) or bool(_nonce)) ` 也没错。

`__get_account_sequence_number` 更贴近要适配STC链的，“如果地址在链上不存，需要给对方提供 auth key 用来收币”

https://github.com/starcoinorg/starcoin-sdk-python/blob/8950bba015d47c0f6f7eb480fe808e195a737a06/starcoin/sdk/client.py#L124-L149

2021-05-26 06:26 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/sdk/serde_types/__init__.py
> +class uint128:
sdk中， 这个文件改动最大。 想着是把 numpy 去掉。

下次如果还有类似情况，我会先把原版放进来，然后会用单独 commit 来记录sdk 的改动。

2021-05-26 07:12 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/sdk/serde_types/__init__.py
> +class uint128:
> 有个问题是sdk现在看起来是整个搬过来，但是其实后面会有维护的问题。如果不能缩小规模（像eth的实现那样只依赖少部分库），那还不如直接就加上这个依赖。

之前没看到这句话，我解释下
- 直接引入官方的 sdk 包， 就必须附加上 numpy， 不确定现有平台能不能支持。 
- numpy 可能会增大打包提及。 我看各个平台上的 whl 文件，都在10 MB 以上。
- eth 我看其实也引入了 eth_abi， eth_account， eth_keys， eth_utils ，不过全是 pure pyton 实现的，没有依赖。所以没啥问题。

2021-05-26 08:03 UTC, huazhouwang commented
@dydysy wallet manager 已经合并，需要关注 chains.json 和 ProviderInterface 的改动

2021-05-27 06:35 UTC, liyanhrxy commented on electrum_gui/common/provider/chains/stc/sdk/serde_types/__init__.py
> +class uint128:
numpy可以的没大问题

2021-05-27 15:53 UTC, taimanhui commented
@dydysy 看 @liyanhrxy 能不能确认下numpy在android和iOS上是否可用（我想应该问题不大），如果暂时不能自己实现交易信息的序列化和反序列化那部分的话，那就先直接依赖官方这个SDK，后面再解决自己实现的问题。

这个PR已经多人看过一遍了，可以重新整理commit再来过一遍review了。

2021-05-27 16:35 UTC, dydysy commented
> @dydysy 看 @liyanhrxy 能不能确认下numpy在android和iOS上是否可用（我想应该问题不大），如果暂时不能自己实现交易信息的序列化和反序列化那部分的话，那就先直接依赖官方这个SDK，后面再解决自己实现的问题。
> 
> 这个PR已经多人看过一遍了，可以重新整理commit再来过一遍review了。

这个 python sdk 没有推送到 pip 仓库。 怎么引入？  requiretment.txt 里面直接 git+https 引入， 会报 没有 hash。

2021-05-28 09:32 UTC, dydysy commented
@taimanhui  @shuaiLiWang @huazhouwang  @liyanhrxy  
已经 rebase 了， 去除本地的 sdk， 代码量少了很多。

2021-05-28 11:31 UTC, huazhouwang commented on electrum_gui/common/coin/configs/chains.json
> +    "bip44_coin_type": 101010,
starcoin 的 bip44 派生规则是怎样的？上次貌似听说他们是基于 Metamask 改的，那应该是派生到 address_index, 那由于 starcoin 是 ed25519，所以需要全路径 hardened。因此需要配置 bip44_last_hardened_level = "ADDRESS_INDEX"

2021-05-28 11:31 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            is_ready=int(time.time()) - block_time < 120,
超过 2 分钟就算掉线？

2021-05-28 11:31 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            outputs=[TransactionOutput(address="0x" + _receiver, value=_value)],
有 token 的情况吗？

2021-05-28 11:31 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/provider.py
> +                ReceiptIdentifier.decode(address)
感觉这种地址解析出结果的 encoding 需要赋上 BECH32

2021-05-28 11:31 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/provider.py
> +        raise NotImplementedError()
starcoin 通过 RPC 获取不到 token 信息吗？

2021-05-28 11:31 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/test_provider.py
> +        self.assertEqual(
这里我有个疑问，你知道 assertEqual 方法到底哪个参数是 expected 哪个参数是 actual？我看官方文档用法是第一个是 actual，第二个是 expected；但我用 Pycharm 运行却发现第一个是 expected ，第二个是 acutal。我上网找答案，有人说是 Pycharm 弄错了。有点懵

2021-05-28 12:30 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/test_provider.py
> +        self.assertEqual(
同懵，我看log ，  他分expect 和 acture ，  我按照字面意思就调整了下，不然有点反应不过来。

我当时也看函数介绍， 只分 first  和 second 了。 所以就把预期的放前面了。

2021-05-28 12:32 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            is_ready=int(time.time()) - block_time < 120,
3 s 一个块。  比eth 还快。 
不过测试网络，现在有点问题，之前挖矿测试积累了难度，现在没人挖了，不出块

2021-05-28 12:37 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/provider.py
> +        raise NotImplementedError()
https://playground.open-rpc.org/?schemaUrl=https://developer.starcoin.org/rpc/schema/contract.json

我猜测可能会和这个接口有关系， 但是没有example， 也没有文档。 而且这个接口也不一定能拿到想要的信息。就没做这个了。

2021-05-28 12:41 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/provider.py
> +                ReceiptIdentifier.decode(address)
ok，  没发现还有个 encoding。

2021-05-28 13:02 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            outputs=[TransactionOutput(address="0x" + _receiver, value=_value)],
什么意思？ 
这个地方，我仿的 eth。需要提取出 token 信息吗？

2021-05-28 13:15 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/test_provider.py
> +        self.assertEqual(
https://github.com/google/pinject/blob/93b7e7a0ef1cf61ae7e267b0ff269024352d0f07/tests/binding_keys_test.py#L73-L84
要不我们参考下 google 的项目

2021-05-28 13:38 UTC, dydysy commented on electrum_gui/common/coin/configs/chains.json
> +    "bip44_coin_type": 101010,
fee_price_decimals_for_legibility   我看到还有这个参数。   stc 就是 9位小数，所以就不用设置了吧？

2021-05-28 14:15 UTC, huazhouwang commented on electrum_gui/common/coin/configs/chains.json
> +    "bip44_coin_type": 101010,
starcoin 习惯怎么表示 gas price? 例如 eth 上 gas price 的单位一般是 gwei

2021-05-28 14:19 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            outputs=[TransactionOutput(address="0x" + _receiver, value=_value)],
geth 只能获取原始的交易信息，我不确定 starcoin 的 rpc 能否获取到 token 的交易信息，如果可以的话，在TransactionInput，TransactionOutput 有个 token_address 表示 token 转账

2021-05-28 14:20 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/test_provider.py
> +        self.assertEqual(
好的，后续我把我的都改过来

2021-05-28 14:36 UTC, dydysy commented on electrum_gui/common/coin/configs/chains.json
> +    "bip44_coin_type": 101010,
max_gas_amount=10000000,
        gas_unit_price=1

        gas Price 单位是 1 nano STC， 合 0.000000001 STC

2021-05-28 16:00 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            outputs=[TransactionOutput(address="0x" + _receiver, value=_value)],
测试网不出块，正式网络也找不到一个token 交易。 暂时没办法确认。

2021-05-30 16:26 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +    def __get_account_sequence_number(self, addr: str) -> int:
一个下划线前缀就可以

2021-05-30 16:26 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        return seq_number
`return max(resource.sequence_number, next_sequence_number or 0)`应该就可以了，不过无所谓一定要这么改。但是这里的`next_sequece_number`是表示什么意思的，什么情况下会比state里面的sequence_number大需要说明下。

2021-05-30 16:26 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +    def __get_account_token(self, addr: str, contract_address: str) -> int:
同样，单下划线

另外为什么这里的返回值是`int`，这个方法的用途是取余额吗？那应该是`_get_account_token_balance`

2021-05-30 16:26 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            _balance = self.__get_account_token(address, f"{stc_utils.CORE_CODE_ADDRESS}::STC::STC")
合并到上面`_nonce`赋值的那行就可以了

2021-05-30 16:26 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            return self.__get_account_token(address, f"{stc_utils.CORE_CODE_ADDRESS}::STC::STC")
注意到这个`f"{stc_utils.CORE_CODE_ADDRESS}::STC::STC"`有几处使用了，考虑作为常量即可。

另外可以把这个常量直接作为`contract_address`的默认值吧，这样子`__get_account_token`也不需要了，直接让`get_address`调用`get_balance`即可

2021-05-30 16:26 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            payload_oj = starcoin_stdlib.decode_script_function_payload(_payload)
oj是obj？

2021-05-30 16:26 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/test_provider.py
> +        self.assertEqual(
官方文档应该没区分expected和actual，我自己实际用的习惯是预期值放在第一个，实际执行结果放第二个，记得有些复杂的执行失败之后报错会出现excepted和actual的字样的。不过我也忘了这个习惯是从那带来的了，但是接触过的很多项目的测试是这么写的

2021-05-30 16:37 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        return seq_number
因为这里需要从txpool获取 seq，否则连续发送的时候，会出现交易被覆盖。

2021-05-30 16:39 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            payload_oj = starcoin_stdlib.decode_script_function_payload(_payload)
这个当时有点随意，在验证代码。没想好名称，是object的意思。

2021-05-31 02:23 UTC, huazhouwang submitted a review, later dismissed
建议实际通过 console 接口走一遍创建钱包-获取余额-预估费率-签名交易上链流程

2021-05-31 03:29 UTC, dydysy commented
> 获取余额
@huazhouwang 
  例如MIGRATED_COINS 要设置一下？ 这个是我们自己写入代码，还是 APP 会自己设置？

2021-05-31 04:02 UTC, huazhouwang commented
> > 获取余额
> 
> 
> 
> @huazhouwang 
> 
>   例如MIGRATED_COINS 要设置一下？ 这个是我们自己写入代码，还是 APP 会自己设置？

你自己设置

2021-05-31 04:58 UTC, dydysy commented
@taimanhui @huazhouwang 

在 console.py 里,  App的调用过程，接新链的时候哪些需要做补充，调整。 可不可以用 uinttest 的方式来标注下。 

例如我看到 list_wallets 方法，里面的币种类型可能就需要改。 我这样去找怕有遗漏，而且效率低。

2021-05-31 05:01 UTC, huazhouwang commented
你应该只需要加 MIGRATED_COINS 就好了吧

2021-05-31 05:05 UTC, dydysy commented
https://github.com/OneKeyHQ/electrum/blob/9de4bc5efc903ec285b6d9ec2c32774c47db9988/electrum_gui/android/console.py#L4653-L4660

这里的 list_wallet 是废弃了么？ 我看这里是要添加 cointype 的吧。

2021-05-31 05:19 UTC, huazhouwang commented
我还真不知道这里的 _type 做什么的， @taimanhui @shuaiLiWang 帮忙看下要怎么弄

2021-05-31 06:24 UTC, taimanhui commented
> 这里的 list_wallet 是废弃了么？ 我看这里是要添加 cointype 的吧。

`list_wallet`还没废弃，需要添加cointype，其实是chain_code。但是`list_wallet`在之后是要废弃的，参见 OneKeyHQ/TaskHub#1679

2021-05-31 06:25 UTC, shuaiLiWang commented
> 我还真不知道这里的 _type 做什么的， @taimanhui @shuaiLiWang 帮忙看下要怎么弄

_type是根据类型获取钱包 比如说只获取BTC的钱包 因为最近不是在搞前后端分离 我们是不是直接返回所有钱包信息 他们自己根据需求排序显示就好

2021-05-31 07:29 UTC, huazhouwang commented
@taimanhui @shuaiLiWang  这么改可以吗？ https://github.com/OneKeyHQ/electrum/pull/769

2021-05-31 07:44 UTC, taimanhui commented
> @taimanhui @shuaiLiWang  这么改可以吗？ https://github.com/OneKeyHQ/electrum/pull/769

可以，是个workaround，这样子短期内就不用再增加一个链扩展一次这个列表了（虽然后者也不算麻烦）

2021-05-31 09:29 UTC, shuaiLiWang commented
> @taimanhui @shuaiLiWang 这么改可以吗？ #769

electrum_gui/android/wallet_context.py中还有一处需要修改 L15

2021-05-31 10:35 UTC, dydysy commented
还有 hd recover 的流程，是也要适配吧？   @taimanhui @huazhouwang

2021-05-31 11:20 UTC, huazhouwang commented
> 还有 hd recover 的流程，是也要适配吧？   @taimanhui @huazhouwang 

我没想好，我担心这样控制不好时间，徒增恢复钱包的耗时。 @taimanhui 决定吧

2021-05-31 15:05 UTC, taimanhui commented
> 还有 hd recover 的流程，是也要适配吧？ @taimanhui @huazhouwang

可以先不用管，后面看产品怎么决定，如果每个新链都增加一部分recover流程肯定不理想，其实应该recover之前先选择才对。

2021-05-31 17:28 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/provider.py
> +            txid="0x" + stc_utils.transaction_hash(signed_tx),
都检查了下， 余额，费率，交易，广播， 都ok。

除了此处本地计算 txid， 和接口返回的 txid 不一致。   明天找他们问问。

2021-06-01 02:14 UTC, huazhouwang commented on electrum_gui/android/console.py
> +        elif type_ in ("btc", "eth", "bsc", "heco", "okt", "stc"):
这里可以不用动，https://github.com/OneKeyHQ/electrum/pull/769 已经处理了

2021-06-01 02:25 UTC, dydysy commented on electrum_gui/android/console.py
> +        elif type_ in ("btc", "eth", "bsc", "heco", "okt", "stc"):
我自己测试用的， 如果到时候我这边rebase有冲突，我就去掉。没有冲突，你那个pr 可以 rebase 的时候干掉就行了。

还有使用测试网络的话， MIGRATED_COINS 是不是也要加个 tstc 才行？ 感觉有点混乱，我commit 的时候就没加tstc了，还是有其他方法测试？

2021-06-01 02:50 UTC, huazhouwang commented on electrum_gui/android/console.py
> +        elif type_ in ("btc", "eth", "bsc", "heco", "okt", "stc"):
不需要加 tstc，这里的 MIGRATED_COINS 是顺着原来架构的逻辑来的，主网和测试网在启动时就区分了，只有 coin 的概念，所以只需要填 stc

2021-06-01 04:22 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/provider.py
> +            txid="0x" + stc_utils.transaction_hash(signed_tx),
txid  查了他们的 dart, js sdk 

已经修复了。

2021-06-01 04:26 UTC, huazhouwang commented
我理解这个 PR rebase 后没问题就可以合并了吧？合并后前端开始适配？

2021-06-01 04:30 UTC, dydysy commented
可以的， 等下我整理后，你们在看下。

2021-06-01 07:06 UTC, huazhouwang submitted a review, later dismissed

2021-06-01 07:20 UTC, dydysy commented
还差个 icon 链接， 我在找@kangshuo要了。

2021-06-01 08:26 UTC, taimanhui reviewed
看起来是就差那个icon了，如果还有缺漏的话后面继续完善吧

另外你@错人了， @sskkss 才是...

2021-06-01 08:26 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +    __MAIN_COIN_SYMBOL = f"{stc_utils.CORE_CODE_ADDRESS}::STC::STC"
你得养成不要用双下划线开头的习惯，在python里这么做意义不大，如果是用来区分不对外的一个下划线就够了，日常除了`__init__`之外很少见到有两个下划线开头的任何东西才是。另外这个常量也不需要定义在类里面，直接放外层文件里就可以了，其实就是一个辅助的符号而已，和这个类具体关系不大...

2021-06-01 08:36 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +    __MAIN_COIN_SYMBOL = f"{stc_utils.CORE_CODE_ADDRESS}::STC::STC"
我看其他有地方这么写，就无脑拿过来了。 

不过仔细想想，我这个地方的 SYMBOL 的确没必要做成私有属性。 是完全可以放开给其他地方使用的。

等下我一起改了。  

另外解释下， `@kangshuo` 是我直接拼的，因为我跟他在slack 上在沟通。 这里没想真的@他 。

2021-06-01 08:38 UTC, taimanhui commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +    __MAIN_COIN_SYMBOL = f"{stc_utils.CORE_CODE_ADDRESS}::STC::STC"
github自动转了之后会@到外部不相关的人（如果有那个id的话），对被你错@的那个用户不太友好...

2021-06-01 09:36 UTC, dydysy commented
icon 先不配置了吧。 下次需要再提pr。

2021-06-01 09:52 UTC, huazhouwang reviewed
另外貌似没有实现 search_txs_by_address 接口，也就意味着无法展示交易历史，是打算后续加吗？

2021-06-01 09:52 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            gas_used = None
pending 时候 gas_used = gas_limit，这个属性不能为 None，接口需要用到

2021-06-01 09:59 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            gas_used = None
我前面刚去掉 。

search_txs_by_address   后续加吧。  现在 rpc 没有接口，只能抓他们浏览器的接口。

2021-06-01 10:05 UTC, huazhouwang approved these changes

2021-06-01 10:12 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            used=gas_used or gas_limit,
在上面一点说了， pending 的时候，也需要 gas_used 数据。

2021-06-01 10:15 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            used=gas_used or gas_limit,
这是参考了 MetaMask 的行为，产品也了解这情况

2021-06-02 06:27 UTC, liyanhrxy commented
> @dydysy 看 @liyanhrxy 能不能确认下numpy在android和iOS上是否可用（我想应该问题不大），如果暂时不能自己实现交易信息的序列化和反序列化那部分的话，那就先直接依赖官方这个SDK，后面再解决自己实现的问题。
> 
> 这个PR已经多人看过一遍了，可以重新整理commit再来过一遍review了。

@taimanhui  numpy安卓是支持的，iOS需要验证，pynacl在iOS设备上出了兼容问题，很头疼

2021-06-03 07:54 UTC, shuaiLiWang commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        normal = int(max(slow * 1, min_wei))
这个normal和slow都是一样的吗

2021-06-03 07:54 UTC, shuaiLiWang commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            slow=EstimatedTimeOnPrice(price=slow, time=600),
另外 这个time是怎么算出来的

2021-06-03 07:54 UTC, shuaiLiWang commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
这个需要在contrib/deterministic-build/requirements.txt下或者requirement_android.txt下添加库 因为android端python库下载是走的这里 ios的 @liyanhrxy 看下加在哪儿

2021-06-03 08:02 UTC, liyanhrxy commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
@dydysy 这个文件里面不支持这个语法（chaquo插件的问题），你可以试下

2021-06-03 08:04 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +        normal = int(max(slow * 1, min_wei))
现在没有快慢之分，链上交易不多。手续费高低不影响上链打包速度

2021-06-03 08:10 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            slow=EstimatedTimeOnPrice(price=slow, time=600),
@huazhouwang   这个是预估时间吧。我只给一个normal ，行不行？

如果APP 要使用这个时间做参考的话，我得改下。 不过现在是慢中快选项，都没有任何区别。

2021-06-03 08:15 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            slow=EstimatedTimeOnPrice(price=slow, time=600),
应该大部分最新的链出块速度都很快，确认时间的区别不大。
但你依然可以像现在这样大概提供个 slow，normal，fast 三个选项，时间大概预估下，具体前端怎么展示，用哪个来展示，由产品确认。例如产品也觉得既然区别不大，只显示一个的话，前端只用 fast 那项就好

2021-06-03 08:17 UTC, dydysy commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
> 这个文件里面不支持这个语法（chaquo插件的问题），你可以试下  

@taimanhui 要不还是把 starcoin 的 sdk 放回 electrum 中去？ numpy 在 ios 导入也不确定能行。

2021-06-03 08:47 UTC, dydysy commented on electrum_gui/common/provider/chains/stc/clients/jsonrpc.py
> +            slow=EstimatedTimeOnPrice(price=slow, time=600),
> 这个time是怎么算出来的
改了， 前面值不对。 现在任何交易， price 大于 1 的情况下，确认速度都是一样的。

2021-06-03 09:26 UTC, taimanhui commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
尽量不要混到electrum中来，如果numpy和requirements的方式都不好处理的话，fork一下stc的sdk到我们这边来，然后用submodule的方式引入到electrum这边来，这样子对numpy的修改提交另外的PR到我们fork的stc sdk仓库就有得跟踪。

我花时间去看了下stc里面serialize和deserialize相关的东西，以目前用到的部分最终去掉这个submodule然后手写需要的内容还是可行的，因为我们用到的部分实在有限，照顾一个sdk然后不断需要考虑更新和同步还是不太理想

2021-06-03 13:54 UTC, dydysy commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
https://github.com/OneKeyHQ/starcoin-sdk-python/commit/fa4548f6d5668fc395f01fc6d70f1ed57456bf29

去掉了 numpy ， 用的 ctypes， 保持和 numpy 结果一致。

@OneKeyHQ/chain  我没注意，先 push 了。 下次有改动，我再提pr。 可以么？

2021-06-03 16:20 UTC, taimanhui commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
不用啊，主要目标是解决requirements里面怎么写的问题而已，requirements.txt应该能直接写路径的，可以先试试看，再不行看看android在pip运行时能不能直接加上也可以

参考（我也是google到的内容）：
- https://pip.pypa.io/en/stable/cli/pip_install/#requirements-file-format
- https://github.com/pypa/pip/issues/5164
- https://github.com/pypa/pip/pull/4208
- https://github.com/pypa/pip/issues/3772

2021-06-03 16:25 UTC, taimanhui commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
再不行的话，把starcoin的sdk打包成wheel直接放仓库里面也行...[至少这个chaquopy一定支持的...](https://chaquo.com/chaquopy/doc/current/android.html#requirements)

两件事情：
- 自己维护一个starcoin的sdk仓库 -> 解决numpy可能不行的问题
- submodule或者wheel -> 解决这个模块不在pypi上导致chaquopy可能装不上的问题

2021-06-04 04:05 UTC, danielsocials commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
放electrum或者submodule里不合适，也没必要，requirement的方式就应该可以， 另外ios numpy也应该没问题，@liyanhrxy pyto不是已经支持了么？

2021-06-04 04:17 UTC, taimanhui commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
如果numpy可以用那就没必要自己维护这个仓库了，requirements某些语法不支持的话发布前打包成wheel就足够满足安装需要了

2021-06-04 07:11 UTC, danielsocials commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
requirements也支持直接从github安装，我们好像以前有库就是这么做的

2021-06-04 11:55 UTC, taimanhui commented on contrib/requirements/requirements.txt
> +git+https://github.com/starcoinorg/starcoin-sdk-python@v1.0.1
带vcs的和wheel都不行，都会默认需要hash，chaquopy用的也是一个很久以前的pip所以不好找解决方案，看起来最终可能要和python-trezor一样处理...

2021-06-06 05:28 UTC, huazhouwang approved these changes

2021-06-07 15:17 UTC, huazhouwang commented on contrib/deterministic-build/requirements-starcoin.txt
> +cryptography==3.3.2 --hash=sha256:c8e8baaf64789e5db7bd931b71051206af345d362e45fb2024a59592495333ef
这里的依赖还有哪些需要保留吗？

2021-06-07 15:17 UTC, huazhouwang commented on electrum_gui/common/provider/chains/stc/sdk/utils/utils.py
> +    """convert cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PublicKey into bytes"""
这里的注释可以换下了

2021-06-07 15:21 UTC, dydysy commented on contrib/deterministic-build/requirements-starcoin.txt
> +cryptography==3.3.2 --hash=sha256:c8e8baaf64789e5db7bd931b71051206af345d362e45fb2024a59592495333ef
要去掉。

2021-06-08 02:50 UTC, huazhouwang approved these changes

2021-06-08 15:34 UTC, taimanhui submitted a review, later dismissed

2021-06-09 03:36 UTC, huazhouwang commented
@dydysy @liyanhrxy  你们俩配合下？谁先 rebase 后合了吧，等你们合后， https://github.com/OneKeyHQ/electrum/pull/777 再rebase 然后迁移测试用例

2021-06-09 03:41 UTC, dydysy commented
> @dydysy @liyanhrxy 你们俩配合下？谁先 rebase 后合了吧，等你们合后， #777 再rebase 然后迁移测试用例

刚刚才注意到。

2021-06-09 03:48 UTC, huazhouwang submitted a review, later dismissed

2021-06-09 03:57 UTC, huazhouwang commented
@shuaiLiWang @liyanhrxy @taimanhui 谁有空看下

2021-06-09 07:35 UTC, dydysy commented
前面那个rebase ，有2点改动。

1，starcoin_types 删除了除 ScriptFunctionCall__PeerToPeer， ScriptFunctionCall__AcceptToken 两种交易之外的所有交易类型。大概去掉了1000多行代码吧。
2， 迁移test。

2021-06-09 11:41 UTC, huazhouwang submitted a review, later dismissed

2021-06-09 15:50 UTC, taimanhui requested changes

2021-06-09 15:50 UTC, taimanhui commented on electrum_gui/common/coin/configs/chains.json
> +        "class": "STCJsonRPC",
乱入了这个`class`和`url`属性，jsonrpc和币种信息没关系，参考其他币种的clients写法

2021-06-09 15:50 UTC, taimanhui commented on electrum_gui/common/coin/configs/testnet_chains.json
> +        "class": "STCJsonRPC",
ditto

2021-06-09 15:59 UTC, dydysy commented on electrum_gui/common/coin/configs/testnet_chains.json
> +        "class": "STCJsonRPC",
electrum_gui/common/coin/codes.py

顺便这个文件也加了2行

2021-06-09 16:19 UTC, dydysy commented on electrum_gui/common/coin/configs/chains.json
> +        "class": "STCJsonRPC",
应该是 sol 合进去后，我这里rebase 解决代码冲突，结构搞乱了。

2021-06-09 16:51 UTC, taimanhui approved these changes

2021-06-09 16:52 UTC, huazhouwang approved these changes

2021-06-09 16:53 UTC, merged